-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME,RI.FOOD_TYPE, RI.FAVORITES,RI.ADDRESS,
ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO RI 
INNER JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, RI.FAVORITES DESC


/*SELECT DISTINCT 
       a.REST_ID, 
       a.REST_NAME, 
       a.FOOD_TYPE, 
       a.FAVORITES, 
       a.ADDRESS, 
       ROUND(AVG(b.REVIEW_SCORE) OVER (PARTITION BY a.REST_ID), 2) AS SCORE
  FROM REST_INFO a
 INNER JOIN REST_REVIEW b ON a.REST_ID = b.REST_ID
 WHERE a.ADDRESS LIKE '서울%'
 ORDER BY SCORE DESC, a.FAVORITES DESC;*/