-- 코드를 입력하세요
SELECT UU.USER_ID, UU.NICKNAME, UB.TOTAL_SALES
FROM USED_GOODS_USER AS UU
INNER JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000) AS UB
ON UU.USER_ID = UB.WRITER_ID
ORDER BY TOTAL_SALES ASC