-- 코드를 입력하세요
SELECT  FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
  FROM  FOOD_PRODUCT FP
  JOIN  (SELECT  CATEGORY, MAX(PRICE) MAX_PRICE
          FROM  FOOD_PRODUCT FP
         GROUP BY  CATEGORY) M_FP
    ON  FP.CATEGORY = M_FP.CATEGORY
        AND FP.PRICE = M_FP.MAX_PRICE
 WHERE  1=1 AND FP.CATEGORY IN ('과자', '국', '김치', '식용유')
 ORDER BY  MAX_PRICE DESC